@startuml

skin rose

title Types - Class Diagram


skinparam componentStyle uml2


Class server {
    +attach(User user) : void
    +initialize()
    +run()
    +shutdown()
}

Class ClientListener <<Thread>> {
    -mServerDispatcher : ServerDispatcher
    -mClientInfo: ClientInfo
    -min:BufferedReader
    +ClientListener()
    +run() : void
} 

Class ClientSender <<Thread>> { 
    -mMessageQueue : Vector
    -mClientInfo : ClientInfo
    -mOut: PrintWriter
    +ClientSender()
    +sendMessage() : void
    -sendMessageToClient() : void
    +run() : void
    +nextMessageFromQueue : String
}

Class ClientInfo {
    +mSocket : Socket
    +mClientListener:ClientListener
    +mClientSender:ClientSender
}

Class mainChatServer {
    +LISTENING_PORT : int
    +main() : void
}

Class ServerDispatcher <<Thread>> {
    -mMessageQueue : Vector
    -mClients : Vector
    -mServerDispatcher:ClientSender
    +addClient() : void
    +deleteClient() : void
    +dispatchMessage() : void
    -sendMessageToAllClients() : void
    +run() : void
    +nextMessageFromQueue() : String
}

@enduml